[[plugins]]
  package = "@netlify/plugin-nextjs"

  [[plugins]]
  package = "netlify-plugin-cypress"

  [dev] 
    command = "next dev"
    targetPort = 3000

[build]
  publish = ".next"
  command = "npm run build"
  # cache Cypress binary in local "node_modules" folder
  # so Netlify caches it
  CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
  # set TERM variable for terminal output
  TERM = "xterm"
