[[plugins]]
  package = "@netlify/plugin-nextjs"

  [[plugins]]
  package = "netlify-plugin-cypress"
  [plugins.inputs]
    # skip the default tests before the deploy
    skip = true
  [plugins.inputs.onSuccess]
    # run tests after the deploy
    enable = true

  [dev] 
    command = "next dev"
    targetPort = 3000

[build]
  publish = ".next"
  command = "npm run build"
  # cache Cypress binary in local "node_modules" folder
  # so Netlify caches it
  CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
  # set TERM variable for terminal output
  TERM = "xterm"
